function T = advection_diffusion_upwind(T, ...
                                        u, ...
                                        v, ...
                                        dt, ...
                                        dx, ...
                                        dy,...
                                        alpha, ...
                                        f)
r = size(T,1);
c = size(T,2);

for i = 2:r-1
    for j = 2:c-1
       T(i,j) = alpha*dt * ( (T(i+1,j)-2*T(i,j)+T(i-1,j))/dx^2 + ...
                (T(i,j+1)-2*T(i,j)+T(i,j-1))/dy^2 ) - ...
                dt * (u(i,j)/dx * (T(i,j)-T(i-1,j)) + ... 
                v(i,j)/dy * (T(i,j)-T(i,j-1)) ) + ...
                T(i,j) + f(i,j)*dt;
    end
end
end